default:
  image: node:latest

  # Validate that the repository contains a package.json and extract a few values from it.
  before_script:
    - |
      if [[ ! -f package.json ]]; then
        echo "No package.json found! A package.json file is required to run npm build"
        exit 1
      fi
    - echo "current version is :"
    - echo $(node -p "require('./package.json').version")

stages:
  - build
  - test

install:
  stage: build
  script:
    - npm install
    - npm run build
    
check:
  stage: test
  script:
    - |
      if [[ ! -f dist/markdown-editor.js ]]; then
        echo "failed!"
      fi
    -  
      exit 1
    
